/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinktreeRouteImport } from './routes/linktree'
import { Route as EcosystemVnfRouteImport } from './routes/ecosystem-vnf'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as IndexRouteImport } from './routes/index'

const LinktreeRoute = LinktreeRouteImport.update({
  id: '/linktree',
  path: '/linktree',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemVnfRoute = EcosystemVnfRouteImport.update({
  id: '/ecosystem-vnf',
  path: '/ecosystem-vnf',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/ecosystem-vnf': typeof EcosystemVnfRoute
  '/linktree': typeof LinktreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/ecosystem-vnf': typeof EcosystemVnfRoute
  '/linktree': typeof LinktreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/ecosystem-vnf': typeof EcosystemVnfRoute
  '/linktree': typeof LinktreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ecosystem' | '/ecosystem-vnf' | '/linktree'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ecosystem' | '/ecosystem-vnf' | '/linktree'
  id: '__root__' | '/' | '/ecosystem' | '/ecosystem-vnf' | '/linktree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcosystemRoute: typeof EcosystemRoute
  EcosystemVnfRoute: typeof EcosystemVnfRoute
  LinktreeRoute: typeof LinktreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/linktree': {
      id: '/linktree'
      path: '/linktree'
      fullPath: '/linktree'
      preLoaderRoute: typeof LinktreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem-vnf': {
      id: '/ecosystem-vnf'
      path: '/ecosystem-vnf'
      fullPath: '/ecosystem-vnf'
      preLoaderRoute: typeof EcosystemVnfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcosystemRoute: EcosystemRoute,
  EcosystemVnfRoute: EcosystemVnfRoute,
  LinktreeRoute: LinktreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
